### ISSUE TITLE
npm install -g restify-gen fails on OSX

### ISSUE THREAD

**Issue by copperorange** [ARSevo/restify-gen#1]
Manually cloning local and running works fine - while attempting to install fails.
Quick snip
....
npm verb linkBins [ { shjs: './bin/shjs' },
npm verb linkBins   '/Users/user/.npm-packages/lib/node_modules/restify-gen/node_modules/.bin',
npm verb linkBins   false ]
npm info linkStuff restify-gen@1.0.6
npm verb linkBins [ { 'restify-gen': 'index.js' },
npm verb linkBins   '/Users/user/.npm-packages/bin',
npm verb linkBins   true ]
npm timing action:build Completed in 12ms
npm verb unlock done using /Users/user/.npm/_locks/staging-72bea977165f4c23.lock for /Users/user/.npm-packages/lib/node_modules/.staging
npm timing stage:rollbackFailedOptional Completed in 42ms
npm timing stage:runTopLevelLifecycles Completed in 929ms
npm verb stack Error: ENOENT: no such file or directory, chmod '/Users/user/.npm-packages/lib/node_modules/restify-gen/index.js'
npm verb cwd /Users/user/Documents/Projects/restify-gen
npm verb Darwin 17.7.0
npm verb argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "------verbose" "-g" "restify-gen"
npm verb node v8.11.3
npm verb npm  v6.2.0
npm ERR! path /Users/user/.npm-packages/lib/node_modules/restify-gen/index.js
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod
npm ERR! enoent ENOENT: no such file or directory, chmod '/Users/user/.npm-packages/lib/node_modules/restify-gen/index.js'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 
npm verb exit [ -2, true ]
npm timing npm Completed in 1190ms

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/user/.npm/_logs/2018-07-24T02_16_18_905Z-debug.log

**Comment by Volem** [comment]
Please try the last released package. 
The issue is because of the updated npm version and now restify-gen is compatible with it.

Thanks for the issue
